#ifndef THEME_FLUENT_H
#define THEME_FLUENT_H

#include "colors.h"

#define PRIMARY_LIGHT       COLOR_RGB_HEX(0xC7E0F4)
#define PRIMARY_MAIN        COLOR_RGB_HEX(0x0078D4)
#define PRIMARY_DARK        COLOR_RGB_HEX(0x005A9E)
#define PRIMARY_CONTRAST    COLOR_WHITE

#define SECONDARY_LIGHT     COLOR_RGB_HEX(0xB3B3B3)
#define SECONDARY_MAIN      COLOR_RGB_HEX(0x3C3C43)
#define SECONDARY_DARK      COLOR_RGB_HEX(0x201F1F)
#define SECONDARY_CONTRAST  COLOR_WHITE

#define SUCCESS_LIGHT       COLOR_RGB_HEX(0x94C973)
#define SUCCESS_MAIN        COLOR_RGB_HEX(0x107C10)
#define SUCCESS_DARK        COLOR_RGB_HEX(0x0B6A0B)
#define SUCCESS_CONTRAST    COLOR_WHITE

#define ERROR_LIGHT         COLOR_RGB_HEX(0xF1707B)
#define ERROR_MAIN          COLOR_RGB_HEX(0xD13438)
#define ERROR_DARK          COLOR_RGB_HEX(0xA4262C)
#define ERROR_CONTRAST      COLOR_WHITE

#define WARNING_LIGHT       COLOR_RGB_HEX(0xFFF6B0)
#define WARNING_MAIN        COLOR_RGB_HEX(0xFFD335)
#define WARNING_DARK        COLOR_RGB_HEX(0xFFB900)
#define WARNING_CONTRAST    COLOR_BLACK

#define INFO_LIGHT          COLOR_RGB_HEX(0xC7E0F4)
#define INFO_MAIN           COLOR_RGB_HEX(0x0178D4)
#define INFO_DARK           COLOR_RGB_HEX(0x005A9E)
#define INFO_CONTRAST       COLOR_WHITE

#define GRAY_50             COLOR_RGB_HEX(0xFAF9F8)
#define GRAY_100            COLOR_RGB_HEX(0xF3F2F1)
#define GRAY_200            COLOR_RGB_HEX(0xEDEBE9)
#define GRAY_300            COLOR_RGB_HEX(0xE1DFDD)
#define GRAY_400            COLOR_RGB_HEX(0xC8C6C4)
#define GRAY_500            COLOR_RGB_HEX(0xB3B0AD)
#define GRAY_600            COLOR_RGB_HEX(0x979593)
#define GRAY_700            COLOR_RGB_HEX(0x797775)
#define GRAY_800            COLOR_RGB_HEX(0x605E5C)
#define GRAY_900            COLOR_RGB_HEX(0x201F1F)

#define BACKGROUND_DEFAULT  GRAY_100

#endif // THEME_FLUENT_H