#ifndef THEME_MUI_H
#define THEME_MUI_H

#include "colors.h"

#define PRIMARY_LIGHT       COLOR_RGB_HEX(0x7986CB)
#define PRIMARY_MAIN        COLOR_RGB_HEX(0x3F51B5)
#define PRIMARY_DARK        COLOR_RGB_HEX(0x303F9F)
#define PRIMARY_CONTRAST    COLOR_WHITE

#define SECONDARY_LIGHT     COLOR_RGB_HEX(0xFF4081)
#define SECONDARY_MAIN      COLOR_RGB_HEX(0xF50057)
#define SECONDARY_DARK      COLOR_RGB_HEX(0xC51162)
#define SECONDARY_CONTRAST  COLOR_WHITE

#define SUCCESS_LIGHT       COLOR_RGB_HEX(0x80E27E)
#define SUCCESS_MAIN        COLOR_RGB_HEX(0x4CAF50)
#define SUCCESS_DARK        COLOR_RGB_HEX(0x087F23)
#define SUCCESS_CONTRAST    COLOR_WHITE

#define ERROR_LIGHT         COLOR_RGB_HEX(0xE57373)
#define ERROR_MAIN          COLOR_RGB_HEX(0xF44336)
#define ERROR_DARK          COLOR_RGB_HEX(0xD32F2F)
#define ERROR_CONTRAST      COLOR_WHITE

#define WARNING_LIGHT       COLOR_RGB_HEX(0xFFB74D)
#define WARNING_MAIN        COLOR_RGB_HEX(0xFF9800)
#define WARNING_DARK        COLOR_RGB_HEX(0xF57C00)
#define WARNING_CONTRAST    COLOR_BLACK

#define INFO_LIGHT          COLOR_RGB_HEX(0x64B5F6)
#define INFO_MAIN           COLOR_RGB_HEX(0x2196F3)
#define INFO_DARK           COLOR_RGB_HEX(0x0D47A1)
#define INFO_CONTRAST       COLOR_WHITE

#define GRAY_50             COLOR_RGB_HEX(0xFAFAFA)
#define GRAY_100            COLOR_RGB_HEX(0xF5F5F5)
#define GRAY_200            COLOR_RGB_HEX(0xEEEEEE)
#define GRAY_300            COLOR_RGB_HEX(0xE0E0E0)
#define GRAY_400            COLOR_RGB_HEX(0xBDBDBD)
#define GRAY_500            COLOR_RGB_HEX(0x9E9E9E)
#define GRAY_600            COLOR_RGB_HEX(0x757575)
#define GRAY_700            COLOR_RGB_HEX(0x616161)
#define GRAY_800            COLOR_RGB_HEX(0x424242)
#define GRAY_900            COLOR_RGB_HEX(0x212121)

#define BACKGROUND_DEFAULT  GRAY_100

#endif // THEME_MUI_H