#ifndef SYSCALL_H
#define SYSCALL_H

#include <stdint.h>
#include <stddef.h>

#define SYSCALL_GET_TIME 5
#define SYSCALL_GET_TIME_UP 7

#define SYSCALL_MALLOC 10
#define SYSCALL_REALLOC 11
#define SYSCALL_FREE 12
#define SYSCALL_KMALLOC_STATS 13

#define SYSCALL_GETCHAR 30

#define SYSCALL_POWER_OFF 100
#define SYSCALL_REBOOT 101

#define SYSCALL_PROCESS_CREATE 200
#define SYSCALL_PROCESS_LIST 201
#define SYSCALL_PROCESS_STOP 202
#define SYSCALL_PROCESS_EXIT 203
#define SYSCALL_PROCESS_IS_ALIVE 204
#define SYSCALL_GETPID 205

#define SYSCALL_THREAD_CREATE 250
#define SYSCALL_THREAD_LIST 251
#define SYSCALL_THREAD_STOP 252
#define SYSCALL_REAP_ZOMBIES 253
#define SYSCALL_THREAD_EXIT 254
#define SYSCALL_THREAD_IS_ALIVE 255
#define SYSCALL_THREAD_GET_ERRNO_LOC 256
#define SYSCALL_GETTID 257

#define THROW_AN_EXCEPTION 300

#define SYSCALL_GFX_DRAW_POINT 400
#define SYSCALL_GFX_DRAW_LINE 401
#define SYSCALL_GFX_DRAW_CIRCLE 402
#define SYSCALL_GFX_FILL_CIRCLE 403
#define SYSCALL_GFX_DRAW_RECT 404
#define SYSCALL_GFX_FILL_RECT 405
#define SYSCALL_GFX_CLEAR 406

#define SYSCALL_GFX_UPDATE_SCREEN 407
#define SYSCALL_GFX_DRAW_STRING 408
#define SYSCALL_GFX_GET_TEXT_BOUNDS 409

#define SYSCALL_CHDIR 500
#define SYSCALL_GETCWD 501

#define SYSCALL_FS_MKDIR 600
#define SYSCALL_FS_RMDIR 601
#define SYSCALL_FS_CREATE_FILE 602
#define SYSCALL_FS_REMOVE_ENTRY 603
#define SYSCALL_FS_FIND_IN_DIR 604
#define SYSCALL_FS_GET_ALL_IN_DIR 605
#define SYSCALL_FS_READ 606
#define SYSCALL_FS_WRITE 607
#define SYSCALL_FS_WRITE_FILE_IN_DIR 608
#define SYSCALL_FS_READ_FILE_IN_DIR 609
#define SYSCALL_FS_GET_PARENT_IDX 610
#define SYSCALL_FS_BUILD_PATH 611

#define SYSCALL_DISK_READ_SECTORS 700
#define SYSCALL_DISK_WRITE_SECTORS 701
#define SYSCALL_DISK_GET_SIZE 702

#define SYSCALL_IPC_SEND    800
#define SYSCALL_IPC_RECEIVE 801
#define SYSCALL_IPC_CALL    802

#define SYSCALL_IO_PORT_GRANT  810
#define SYSCALL_IO_PORT_REVOKE 811

#define SYSCALL_VFS_REGISTER 820
#define SYSCALL_VFS_OPEN     821
#define SYSCALL_VFS_READ     822
#define SYSCALL_VFS_WRITE    823
#define SYSCALL_VFS_CLOSE    824
#define SYSCALL_VFS_STAT     825
#define SYSCALL_VFS_MKDIR    826
#define SYSCALL_VFS_RMDIR    827
#define SYSCALL_VFS_UNLINK   828

struct syscall_regs
{
    uint64_t r9;
    uint64_t r8;
    uint64_t r10;
    uint64_t rdx;
    uint64_t rsi;
    uint64_t rdi;
    uint64_t rax;
};

#include "../time/clock/clock.h"
#include "../fs/fs.h"

uintptr_t syscall_handler(const struct syscall_regs *regs);

#endif // SYSCALL_H